- name: Create a group
  group:
    name: cloudadmins
    gid: 2501
    state: present

- name: Create a users
  user: 
    name: "{{item.name}}"
    uid: "{{item.uid}}"
    state: present
    groups: cloudadmins,wheel
    append: yes
    home: /home/"{{item.name}}"

  loop: "{{userlist}}"

- name: Creates a ssh directory
  file:
    path: /home/"{{item.name}}"/.ssh
    state: directory

  loop: "{{userlist}}"

- name: Create a ssh key and distribute it
  community.crypto.openssh_keypair:
    path: /home/"{{item.name}}"/.ssh/
    regenerate: full_idempotence

  loop: "{{userlist}}"