- name: Create first partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 4GiB

- name: Create a xfs file system on /dev/sdb1
  filesystem:
    fstype: xfs
    dev: /dev/sdb1

- name: Create a /part1 directory
  file:
    path: /part1
    state: directory
    mode: '0755'

- name: Mount first partition
  mount:
    path: /part1
    src:  /dev/sdb1
    fstype: xfs
    state: mounted

- name: Create second partition
  parted:
    device: /dev/sdb
    number: 2
    state: present
    part_end: 5GiB

- name: Create a ext4 file system on /dev/sdb1
  filesystem:
    fstype: ext4
    dev: /dev/sdb2

- name: Create a /part2 directory
  file:
    path: /part2
    state: directory
    mode: '0755'

- name: Mount second partition
  mount:
    path: /part2
    src:  /dev/sdb2
    fstype: ext4
    state: mounted

